    const { Model } = require('sequelize');
const { nullable } = require('zod');

module.exports = (sequelize, DataTypes) => {
    class Tasks extends Model {}

Tasks.init(
        {
            id: {
                type: DataTypes.INTEGER,
                autoIncrement: true,
                allowNull: false,
                primaryKey: true,
            },
            theme_id: {
                type: DataTypes.INTEGER,
                allowNull: false,
            },
            solution: {
                type: DataTypes.STRING(150),
                allowNull: false,
            },
            difficulty: {
                type: DataTypes.INTEGER,
                allowNull: false,
            },
            experience_points: {
                type: DataTypes.INTEGER,
                allowNull: false,
                defaultValue: 1
            },
            task_title: {
                type: DataTypes.STRING(250),
                allowNull: false,
            },
            task: {
                type: DataTypes.TEXT,
                allowNull: false, 
            },
			solution_format:{
				type: DataTypes.STRING,
				allowNull: false
			},
            first_hint:{
                type: DataTypes.STRING,
                allowNull: true
            },
            second_hint:{
                type: DataTypes.STRING,
                allowNull: true
            },
            validated:{
                type: DataTypes.TINYINT(1),
                allowNull: false,
                defaultValue:0
            }
        },
        {
            sequelize,
            modelName: 'Tasks',
            tableName: 'tasks',
            timestamps: false,
        }
    );
    Tasks.initializeTasks = async () => {
        const testTasks = [
            {
                id: 1,
                theme_id: 11,
                solution: "120",
                difficulty: 2,
                experience_points: 25,
                task_title: "Gráfelmélet alapok",
                task: "Egy 5 csúcsú összefüggő gráfnak legalább hány éle van?",
                solution_format: "Egész szám",
                first_hint: "Egy fa éleinek száma $n-1$.",
                second_hint: "Összefüggő gráfban legalább annyi él van, mint egy fában.",
                validated:1
            },
            {
                id: 2,
                theme_id: 3,
                solution: "1 2 3",
                difficulty: 2,
                experience_points: 25,
                task_title: "Harmadfokú egyenlet",
                task: "Oldd meg valós számok halmazán: $x^3 - 6x^2 + 11x - 6 = 0$",
                solution_format: "Három szám szóközzel",
                first_hint: "Próbáld megtalálni az egész gyököket az osztók segítségével.",
                second_hint: "A lehetséges gyökök a konstans tag osztói (±1, ±2, ±3, ±6).",
                validated:1
            },
            {
                id: 3,
                theme_id: 9,
                solution: "2",
                difficulty: 2,
                experience_points: 25,
                task_title: "Integrálás",
                task: "Számítsd ki: $\\int_{0}^{1} (3x^2 + 2x) \\, dx$",
                solution_format: "Egész szám",
                first_hint: "Integrálás tagonként: $\\int 3x^2 dx + \\int 2x dx$.",
                second_hint: "A határozott integrál kiszámítása a határok behelyettesítésével.",
                validated:1
            },
            {
                id: 4,
                theme_id: 15,
                solution: "30",
                difficulty: 2,
                experience_points: 25,
                task_title: "Háromszög kerülete",
                task: "Egy egyenlő oldalú háromszög területe $25\\sqrt{3}$ cm². Mennyi a kerülete?",
                solution_format: "Egész szám",
                first_hint: "Az egyenlő oldalú háromszög területe: $\\frac{a^2\\sqrt{3}}{4}$.",
                second_hint: "Oldd meg az egyenletet $a$-ra, majd számítsd ki a kerületet.",
                validated:1
            },
            {
                id: 5,
                theme_id: 18,
                solution: "5",
                difficulty: 2,
                experience_points: 25,
                task_title: "Moduláris egyenlet",
                task: "Oldd meg: $3x \\equiv 1 \\pmod{7}$",
                solution_format: "Egész szám",
                first_hint: "Keress olyan $x$-et, ahol $3x - 1$ osztható 7-tel.",
                second_hint: "Próbálkozz $x=0$-tól $6$-ig.",
                validated:1
            },
        
            {
                id: 6,
                theme_id: 20,
                solution: "100",
                difficulty: 2,
                experience_points: 25,
                task_title: "Térgeometria",
                task: "Egy kocka felszíne 150 cm². Mennyi a térfogata?",
                solution_format: "Egész szám",
                first_hint: "A kocka felszíne: $6a^2$.",
                second_hint: "Először számold ki az él hosszát.",
                validated:1
            },
            {
                id: 7,
                theme_id: 12,
                solution: "k<-2 k>2",
                difficulty: 2,
                experience_points: 25,
                task_title: "Paraméteres egyenlőtlenség",
                task: "Milyen $k$ értékekre lesz az $x^2 + kx + 1 > 0$ egyenlőtlenség minden valós $x$-re igaz?",
                solution_format: "k<-2 k>2 (szóközzel elválasztva)",
                first_hint: "A diszkrimináns legyen negatív.",
                second_hint: "$k^2 - 4 < 0$.",
                validated:1
            },
            {
                id: 8,
                theme_id: 21,
                solution: "0.25",
                difficulty: 2,
                experience_points: 25,
                task_title: "Trigonometrikus azonosság",
                task: "Mennyi $\\sin(15°) \\cdot \\sin(75°)$ értéke? (4 tizedesjegy)",
                solution_format: "Tizedestört",
                first_hint: "Használd a szorzattá alakító képletet: $\\sin A \\sin B = \\frac{1}{2}[\\cos(A-B) - \\cos(A+B)]$.",
                second_hint: "$\\cos(60°) = 0.5$ és $\\cos(90°) = 0$.",
                validated:1
            },
            {
                id: 9,
                theme_id: 16,
                solution: "189",
                difficulty: 2,
                experience_points: 25,
                task_title: "Számtani-mértani sorozat",
                task: "Egy számtani sorozat első tagja 3, differenciája 4. Egy mértani sorozat első tagja 2, kvóciense 3. Hányadik tagjuk lesz egyenlő?",
                solution_format: "Egész szám",
                first_hint: "Állíts fel egyenletet: $3 + 4(n-1) = 2 \\cdot 3^{n-1}$.",
                second_hint: "Próbálkozz $n=1, 2, 3, ...$-nel.",
                validated:1
            },
            {
                id: 10,
                theme_id: 22,
                solution: "0.0001",
                difficulty: 2,
                experience_points: 25,
                task_title: "Valószínűségszámítás",
                task: "Mennyi eséllyel találunk ki egy 4 jegyű PIN-kódot első próbálkozásra?",
                solution_format: "Tizedestört (4 tizedesjegy)",
                first_hint: "Összes lehetséges kód: $10^4$.",
                second_hint: "Csak egy kedvező eset van.",
                validated:1
            },
            {
                id:11,
                theme_id:11,
                solution:"243",
                difficulty:0,
                experience_points: 10,
                task_title: "Egyszerű kombinatorikai feladat speciális dobókockával",
                task:"Egy szabályos játékkocka két oldalára 0-át, két oldalára 2-est, két oldalára 4-est írunk. A dobókockát ötször egymás után feldobjuk, és a dobások eredményét rendre feljegyezzük. Hányféle számötöst jegyezhetünk fel?",
                solution_format:"Egy egész szám, mint például 1.",
                first_hint:"Nem számít a sorrend.",
                second_hint:"3 féle elem van (0, 2, 4) amik ismétlődnek.",
                validated: 1
            },
            {
                id:12,
                theme_id:11,
                solution:"51",
                difficulty:1,
                experience_points: 15,
                task_title: "Kombinatorikai feladat speciális dobókockával",
                task:"Egy szabályos játékkocka két oldalára 0-át, két oldalára 2-est, két oldalára 4-est írunk. A dobókockát ötször egymás után feldobjuk, és a dobások eredményét rendre feljegyezzük. Hányféle számötös esetében lehet a dobott számok összege 10?",
                solution_format:"Egy egész szám, mint például 1.",
                first_hint:"Gondoljon arra, hogyan lehet 10-et kapni a számjegzek összegeként.",
                second_hint:"Vizsgálja meg az eseteket, hány féle képpen dobhatjuk őket?",
                validated: 1
            },
            {
                id:13,
                theme_id:11,
                solution:"20",
                difficulty:0,
                experience_points: 10,
                task_title: "Kombinatorika egy halmazzal",
                task:"Adott az $A = {0;1;2;3;4;5}$ halmaz. Az A halmaz elemeiből hány olyan hatjegyű szám írható fel, amely legalább egy egyest tartalmaz?",
                solution_format:"Egy egész szám, mint például 1.",
                first_hint:"Nem számít a sorrend.",
                second_hint:"Mennyit szeretnénk kiválasytani, mennyiből?",
                validated: 1
            },
            {
                id:14,
                theme_id:11,
                solution:"26380",
                difficulty:1,
                experience_points: 15,
                task_title: "Kombinatorika egy halmazzal",
                task:"Egy 2011-ben készült statisztikai összehasonlításban az alábbiakat olvashattuk:„Ha New York-ban az átlagfizetést és az átlagos árszínvonalat egyaránt 100%-nak veszszük, akkor Budapesten az átlagfizetés 23,6%, az átlagos árszínvonal pedig 70,9%. (Az árszínvonal számításához 122 áru és szolgáltatás árát hasonlították össze.)” Feltételezve, hogy az idézet megállapításai igazak, válaszoljon az alábbi kérdésekre! Ha Budapesten a havi átlagfizetés 150 ezer forint, akkor hány dollár ($) a havi átlagfizetés New York-ban, 190 forint/dollár (Ft/$) árfolyammal számolva? Válaszát egész dollárra kerekítve adja meg! ",
                solution_format:"Egy egész szám, mint például 1.",
                first_hint:"A legalább szó és hány olyan szavak fontos, érdemes ezeken elgondolkozni.",
                second_hint:"Komplementer esemény.",
                validated: 1
            },

            {
                id:15,
                theme_id:11,
                solution:"243",
                difficulty:0,
                experience_points: 10,
                task_title: "Egyszerű kombinatorikai feladat speciális dobókockával",
                task:"Egy szabályos játékkocka két oldalára 0-át, két oldalára 2-est, két oldalára 4-est írunk. A dobókockát ötször egymás után feldobjuk, és a dobások eredményét rendre feljegyezzük. Hányféle számötöst jegyezhetünk fel?",
                solution_format:"Egy egész szám, mint például 1.",
                first_hint:"Nem számít a sorrend.",
                second_hint:"3 féle elem van (0, 2, 4) amik ismétlődnek.",
                validated: 1
            },
            {
                id:16,
                theme_id:11,
                solution:"51",
                difficulty:1,
                experience_points: 15,
                task_title: "Kombinatorikai feladat speciális dobókockával",
                task:"Egy szabályos játékkocka két oldalára 0-át, két oldalára 2-est, két oldalára 4-est írunk. A dobókockát ötször egymás után feldobjuk, és a dobások eredményét rendre feljegyezzük. Hányféle számötös esetében lehet a dobott számok összege 10?",
                solution_format:"Egy egész szám, mint például 1.",
                first_hint:"Gondoljon arra, hogyan lehet 10-et kapni a számjegzek összegeként.",
                second_hint:"Vizsgálja meg az eseteket, hány féle képpen dobhatjuk őket?",
                validated: 1
            },
            {
                id: 17,
                theme_id: 1,
                solution: "6",
                difficulty: 2,
                experience_points: 50,
                task_title: "2020 e. érettségi abszolútérték",
                task: "Mennyi a megoldások összege az $|x - 3| = 7$ egyenletre?",
                solution_format: "Egész szám",
                first_hint: "Az abszolútérték egyenlet két esetre bontható: $x - 3 = 7$ és $x - 3 = -7$.",
                second_hint: "A kapott gyökök: $10$ és $-4$. Összegük?",
                validated: 1
            },
            {
                id: 18,
                theme_id: 2,
                solution: "igaz",
                difficulty: 1,
                experience_points: 25,
                task_title: "Bizonyítás páros négyzete",
                task: "Igaz-e: Ha egy szám páros, akkor a négyzete is páros?",
                solution_format: "igaz/hamis",
                first_hint: "Legyen $n = 2k$ (páros szám). Számítsd ki $n^2$-et.",
                second_hint: "$n^2 = 4k^2$, ami biztosan páros.",
                validated: 1
            },
            {
                id: 19,
                theme_id: 3,
                solution: "5",
                difficulty: 1,
                experience_points: 25,
                task_title: "2021 k. érettségi egyenlet",
                task: "Oldd meg: $3(x - 2) = 2x + 1$",
                solution_format: "Egész szám",
                first_hint: "Bontsd fel a zárójelet: $3x - 6 = 2x + 1$.",
                second_hint: "Vonj ki $2x$-et és adj hozzá 6-ot mindkét oldalhoz.",
                validated: 1
            },
            {
                id: 20,
                theme_id: 4,
                solution: "4,1",
                difficulty: 2,
                experience_points: 50,
                task_title: "2019 e. érettségi egyenletrendszer",
                task: "Oldd meg: $$2x + y = 9$$ $$x - y = 3$$",
                solution_format: "x,y",
                first_hint: "Add össze a két egyenletet az egyik változó kiküszöböléséhez.",
                second_hint: "$3x = 12 → x = 4$. Helyettesíts vissza.",
                validated: 1
            },
            {
                id: 21,
                theme_id: 5,
                solution: "x<=5",
                difficulty: 2,
                experience_points: 50,
                task_title: "2022 oktv egyenlőtlenség",
                task: "Add meg a $3x + 2 ≥ 17$ egyenlőtlenség megoldáshalmazát!",
                solution_format: "Egyenlőtlenség",
                first_hint: "Vonj ki 2-t mindkét oldalból: $3x ≥ 15$.",
                second_hint: "Oszd el 3-mal: $x ≥ 5$.",
                validated: 1
            },
            {
                id: 22,
                theme_id: 6,
                solution: "x^2+3x+2",
                difficulty: 1,
                experience_points: 25,
                task_title: "Kifejezés szorzattá alakítása",
                task: "Alakítsd szorzattá: $x^2 + 5x + 6$",
                solution_format: "Algebrai kifejezés",
                first_hint: "Keress két számot, melyek összege 5, szorzata 6.",
                second_hint: "$(x + 2)(x + 3)$",
                validated: 1
            },
            {
                id: 23,
                theme_id: 7,
                solution: "x!=2",
                difficulty: 1,
                experience_points: 25,
                task_title: "Értelmezési tartomány",
                task: "Add meg az $1/(x - 2)$ függvény értelmezési tartományát!",
                solution_format: "Egyenlőtlenség",
                first_hint: "A nevező nem lehet 0.",
                second_hint: "$x - 2 ≠ 0 → x ≠ 2$",
                validated: 1
            },
            {
                id: 24,
                theme_id: 8,
                solution: "2",
                difficulty: 2,
                experience_points: 50,
                task_title: "2018 e. érettségi logaritmus",
                task: "Oldd meg: $log_2(x) = 3$",
                solution_format: "Egész szám",
                first_hint: "A logaritmus definíciója: $2^3 = x$.",
                second_hint: "$2^3 = 8 → x = 8$",
                validated: 1
            },
            {
                id: 25,
                theme_id: 9,
                solution: "9",
                difficulty: 2,
                experience_points: 50,
                task_title: "Függvény minimuma",
                task: "Mi a minimumértéke az $f(x) = x^2 - 6x + 13$ függvénynek?",
                solution_format: "Egész szám",
                first_hint: "Teljes négyzetté alakítás: $(x - 3)^2 + 4$.",
                second_hint: "A minimum a konstans tag: 4.",
                validated: 0
            },
            {
                id: 26,
                theme_id: 10,
                solution: "3",
                difficulty: 1,
                experience_points: 25,
                task_title: "Halmazok metszete",
                task: "Hány elemű az $A = {1,3,5}$ és $B = {3,5,7}$ halmazok metszete?",
                solution_format: "Egész szám",
                first_hint: "Metszet = közös elemek.",
                second_hint: "$A ∩ B = {3,5}$",
                validated: 1
            },
            {
                id: 27,
                theme_id: 11,
                solution: "60",
                difficulty: 2,
                experience_points: 50,
                task_title: "2020 oktv kombinatorika",
                task: "Hányféleképpen választhatunk ki 3 főt 5 lányból és 5 fiúból úgy, hogy legyen köztük lány is?",
                solution_format: "Egész szám",
                first_hint: "Összes eset mínusz csak fiúk kiválasztása.",
                second_hint: "$C(10,3) - C(5,3) = 120 - 10 = 110$",
                validated: 1
            },
            {
                id: 28,
                theme_id: 12,
                solution: "2",
                difficulty: 2,
                experience_points: 50,
                task_title: "Paraméteres egyenlet",
                task: "Milyen $a$ értékre van az $ax + 4 = 0$ egyenletnek megoldása $x = -2$?",
                solution_format: "Egész szám",
                first_hint: "Helyettesítsd be $x = -2$-t: $a*(-2) + 4 = 0$.",
                second_hint: "$-2a = -4 → a = 2$",
                validated: 1
            },
            {
                id: 29,
                theme_id: 13,
                solution: "13",
                difficulty: 1,
                experience_points: 25,
                task_title: "Távolság számítás",
                task: "Mekkora a (0,0) és (5,12) pontok távolsága?",
                solution_format: "Egész szám",
                first_hint: "Használd a Pitagorasz-tételt: $sqrt(5^2 + 12^2)$.",
                second_hint: "$sqrt(25 + 144) = sqrt(169) = 13$",
                validated: 1
            },
            {
                id: 30,
                theme_id: 14,
                solution: "hamis",
                difficulty: 0,
                experience_points: 15,
                task_title: "Gráf fokszámok",
                task: "Lehet-e egy gráfnak 4 csúcsa és fokszámai: 1, 1, 2, 3?",
                solution_format: "igaz/hamis",
                first_hint: "A fokszámok összege páros kell legyen.",
                second_hint: "1+1+2+3=7 (páratlan), tehát nem lehetséges.",
                validated: 1
            },
            {
                id: 31,
                theme_id: 15,
                solution: "30",
                difficulty: 0,
                experience_points: 15,
                task_title: "Háromszög kerülete",
                task: "Egy derékszögű háromszög befogói 5 cm és 12 cm. Mekkora a kerülete?",
                solution_format: "Egész szám",
                first_hint: "Átfogó kiszámítása Pitagorasz-tétellel: $sqrt(5^2 + 12^2)$.",
                second_hint: "Átfogó = 13 cm. Kerület = 5+12+13 = 30 cm.",
                validated: 1
            },
            {
                id: 32,
                theme_id: 16,
                solution: "15",
                difficulty: 1,
                experience_points: 25,
                task_title: "Számtani sorozat",
                task: "Mi a 8. tagja a 3, 5, 7,... számtani sorozatnak?",
                solution_format: "Egész szám",
                first_hint: "Közönséges differencia: 2. Képlet: $a_n = a_1 + (n-1)d$.",
                second_hint: "$a_8 = 3 + 7*2 = 17$",
                validated: 1
            },
            {
                id: 33,
                theme_id: 17,
                solution: "5",
                difficulty: 0,
                experience_points: 15,
                task_title: "Módusz számítás",
                task: "Mi a módusza a {2, 3, 5, 5, 7} adatsornak?",
                solution_format: "Egész szám",
                first_hint: "A leggyakoribb érték.",
                second_hint: "Az 5 szerepel kétszer.",
                validated: 1
            },
            {
                id: 34,
                theme_id: 18,
                solution: "hamis",
                difficulty: 0,
                experience_points: 15,
                task_title: "Prím számok",
                task: "Igaz-e, hogy 1 prímszám?",
                solution_format: "igaz/hamis",
                first_hint: "Prímszámnak pontosan két osztója van.",
                second_hint: "1-nek csak egy osztója van (önmaga).",
                validated: 1
            },
            {
                id: 35,
                theme_id: 19,
                solution: "6",
                difficulty: 0,
                experience_points: 15,
                task_title: "2023 k. érettségi szöveges",
                task: "Egy téglatest térfogata 120 cm³. Ha két él 4 cm és 5 cm, mekkora a harmadik?",
                solution_format: "Egész szám",
                first_hint: "Térfogat = a×b×c → 4×5×c = 120.",
                second_hint: "20c = 120 → c = 6.",
                validated: 1
            },
            {
                id: 36,
                theme_id: 20,
                solution: "150",
                difficulty: 0,
                experience_points: 15,
                task_title: "Térmértan",
                task: "Egy kocka felszíne 150 cm². Mekkora egy élének hossza?",
                solution_format: "Egész szám",
                first_hint: "A kocka felszíne: $6a^2$.",
                second_hint: "$6a^2 = 150 → a^2 = 25 → a = 5$",
                validated: 1
            },
            {
                id: 37,
                theme_id: 21,
                solution: "1",
                difficulty: 0,
                experience_points: 15,
                task_title: "Trigonometria alapok",
                task: "Mennyi $sin(90°)$ értéke?",
                solution_format: "Egész szám",
                first_hint: "A szinusz függvény értékei egységkörből.",
                second_hint: "$sin(90°) = 1$",
                validated: 1
            },
            {
                id: 38,
                theme_id: 22,
                solution: "0.5",
                difficulty: 0,
                experience_points: 15,
                task_title: "Valószínűség",
                task: "Mekkora valószínűséggel dobunk egy szabályos kockával páros számot?",
                solution_format: "Tizedes tört",
                first_hint: "Kedvező esetek: 3 (2,4,6). Összes eset: 6.",
                second_hint: "$3/6 = 1/2$",
                validated: 1
            },
            {
                id: 39,
                theme_id: 1,
                solution: "2",
                difficulty: 1,
                experience_points: 25,
                task_title: "2017 e. érettségi gyökös",
                task: "Oldd meg: $sqrt{2x + 1} = 3$",
                solution_format: "Egész szám",
                first_hint: "Emeld négyzetre mindkét oldalt: $2x + 1 = 9$.",
                second_hint: "$2x = 8 → x = 4$",
                validated: 1
            },
            {
                id: 40,
                theme_id: 2,
                solution: "hamis",
                difficulty: 0,
                experience_points: 15,
                task_title: "Bizonyítás irracionális",
                task: "Igaz-e: $sqrt{2}$ racionális szám?",
                solution_format: "igaz/hamis",
                first_hint: "Indirekt bizonyítás: feltételezzük, hogy $sqrt{2} = a/b$ (egészek).",
                second_hint: "Ismert tétel: $sqrt{2}$ irracionális.",
                validated: 1
            },
            {
                id: 41,
                theme_id: 3,
                solution: "4",
                difficulty: 0,
                experience_points: 15,
                task_title: "2016 k. érettségi egyenlet",
                task: "Oldd meg: $5x - 7 = 13$",
                solution_format: "Egész szám",
                first_hint: "Adj hozzá 7-et mindkét oldalhoz: $5x = 20$.",
                second_hint: "Oszd el 5-tel: $x = 4$.",
                validated: 1
            },
            {
                id: 42,
                theme_id: 4,
                solution: "3,-1",
                difficulty: 1,
                experience_points: 25,
                task_title: "Egyenletrendszer",
                task: "Oldd meg: $$x + 2y = 1$$ $$3x - y = 10$$",
                solution_format: "x,y",
                first_hint: "Szorozd meg a második egyenletet 2-vel, majd add össze az elsővel.",
                second_hint: "$7x = 21 → x = 3$. Helyettesíts vissza y-ra.",
                validated: 1
            },
            {
                id: 43,
                theme_id: 5,
                solution: "x<4",
                difficulty: 1,
                experience_points: 25,
                task_title: "Egyenlőtlenség",
                task: "Mi a megoldása a $-2x + 5 > -3$ egyenlőtlenségnek?",
                solution_format: "Egyenlőtlenség",
                first_hint: "Vonj ki 5-öt: $-2x > -8$.",
                second_hint: "Oszd el (-2)-vel, figyelve az egyenlőtlenség irányváltására.",
                validated: 1
            },
            {
                id: 44,
                theme_id: 6,
                solution: "x^3",
                difficulty: 0,
                experience_points: 15,
                task_title: "Kifejezés egyszerűsítése",
                task: "Egyszerűsítsd: $(x^5)/(x^2)$",
                solution_format: "Algebrai kifejezés, például x^42",
                first_hint: "Azonos alapú hatványok osztása: kitevők kivonása.",
                second_hint: "$x^{5-2} = x^3$",
                validated: 1
            },
            {
                id: 45,
                theme_id: 1,
                solution: "-8",
                difficulty: 0,
                experience_points: 15,
                task_title: "Abszolútérték összeg",
                task: "Mennyi a megoldások összege az $|x + 4| = 9$ egyenletre?",
                solution_format: "Egész szám",
                first_hint: "Bontsd két esetre: $x + 4 = 9$ és $x + 4 = -9$.",
                second_hint: "Gyökök: $5$ és $-13$. Összegük?",
                validated: 1
            },
            {
                id: 46,
                theme_id: 2,
                solution: "igaz",
                difficulty: 0,
                experience_points: 15,
                task_title: "Páratlan négyzet",
                task: "Igaz-e: Ha $a^2$ páratlan, akkor $a$ is páratlan?",
                solution_format: "igaz/hamis",
                first_hint: "Indirekt bizonyítás: tegyük fel, hogy $a$ páros.",
                second_hint: "Páros szám négyzete páros, ellentmondás.",
                validated: 1
            },
            {
                id: 47,
                theme_id: 3,
                solution: "7",
                difficulty: 1,
                experience_points: 25,
                task_title: "2020 k. érettségi",
                task: "Oldd meg: $2(x + 3) = 3x - 1$",
                solution_format: "Egész szám",
                first_hint: "Bontsd fel a zárójelet: $2x + 6 = 3x - 1$.",
                second_hint: "Vonj ki $2x$-et és adj hozzá 1-et.",
                validated: 1
            },
            {
                id: 48,
                theme_id: 4,
                solution: "2,-1",
                difficulty: 2,
                experience_points: 50,
                task_title: "Egyenletrendszer",
                task: "Oldd meg: $$3x + y = 5$$ $$x - 2y = 4$$",
                solution_format: "x,y",
                first_hint: "Szorozd az első egyenletet 2-vel: $6x + 2y = 10$.",
                second_hint: "Add össze a második egyenlettel: $7x = 14 → x=2$.",
                validated: 1
            },
            {
                id: 49,
                theme_id: 5,
                solution: "x<=-2",
                difficulty: 0,
                experience_points: 25,
                task_title: "Egyenlőtlenség",
                task: "Mi a megoldása a $-3x ≥ 6$ egyenlőtlenségnek?",
                solution_format: "Egyenlőtlenség",
                first_hint: "Oszd el (-3)-mal, figyelve az irányváltásra.",
                second_hint: "x ≤ -2",
                validated: 1
            },
            {
                id: 50,
                theme_id: 6,
                solution: "(x-4)(x+3)",
                difficulty: 0,
                experience_points: 25,
                task_title: "Másodfokú szorzattá",
                task: "Alakítsd szorzattá: $x^2 - x - 12$",
                solution_format: "Algebrai kifejezés",
                first_hint: "Keress két számot, melyek összege -1, szorzata -12.",
                second_hint: "A számok: -4 és 3.",
                validated: 1
            },
            {
                id: 51,
                theme_id: 7,
                solution: "x>=-1",
                difficulty: 1,
                experience_points: 50,
                task_title: "Gyökös értelmezési tartomány",
                task: "Add meg a $sqrt{x + 1}$ függvény értelmezési tartományát!",
                solution_format: "Egyenlőtlenség",
                first_hint: "A gyökjel alatti kifejezés ≥ 0.",
                second_hint: "x + 1 ≥ 0 → x ≥ -1",
                validated: 1
            },
            {
                id: 52,
                theme_id: 8,
                solution: "1000",
                difficulty: 0,
                experience_points: 25,
                task_title: "Logaritmus alap",
                task: "Oldd meg: $log_{10}(x) = 3$",
                solution_format: "Egész szám",
                first_hint: "A logaritmus definíciója: $10^3 = x$.",
                second_hint: "10³ = 1000",
                validated: 1
            },
            {
                id: 53,
                theme_id: 9,
                solution: "-1",
                difficulty: 0,
                experience_points: 50,
                task_title: "Függvény zérushely",
                task: "Hol metszi az x-tengelyt az $f(x) = x^2 + 2x - 3$ függvény?",
                solution_format: "Egész szám",
                first_hint: "Oldd meg a $x^2 + 2x - 3 = 0$ egyenletet.",
                second_hint: "Szorzattá alakítás: $(x+3)(x-1)=0$. Válaszd a kisebb gyököt.",
                validated: 1
            },
            {
                id: 54,
                theme_id: 10,
                solution: "6",
                difficulty: 0,
                experience_points: 25,
                task_title: "Halmazok uniója",
                task: "Hány elemű {1,2,3} ∪ {3,4,5,6}?",
                solution_format: "Egész szám",
                first_hint: "Unió = összes különböző elem.",
                second_hint: "{1,2,3,4,5,6} → 6 elem",
                validated: 1
            },
            {
                id: 55,
                theme_id: 11,
                solution: "10",
                difficulty: 1,
                experience_points: 25,
                task_title: "Kombinatorikai alap",
                task: "Hányféleképpen választhatsz 2 könyvet 5-ből?",
                solution_format: "Egész szám",
                first_hint: "Kombináció: $C(5,2)$.",
                second_hint: "$5×4/2 = 10$",
                validated: 1
            },
            {
                id: 56,
                theme_id: 12,
                solution: "5",
                difficulty: 1,
                experience_points: 50,
                task_title: "Paraméteres egyenlet",
                task: "Milyen $k$ értékre lesz a $kx - 10 = 0$ egyenlet megoldása $x=2$?",
                solution_format: "Egész szám",
                first_hint: "Helyettesítsd be $x=2$-t: $2k = 10$.",
                second_hint: "k = 5",
                validated: 1
            },
            {
                id: 57,
                theme_id: 13,
                solution: "5",
                difficulty: 1,
                experience_points: 25,
                task_title: "Távolság számítás",
                task: "Mekkora a (3,4) pont távolsága az origótól?",
                solution_format: "Egész szám",
                first_hint: "Használd a távolságképletet: $sqrt{3^2 + 4^2}$.",
                second_hint: "5 egység (3-4-5 háromszög)",
                validated: 1
            },
            {
                id: 58,
                theme_id: 14,
                solution: "hamis",
                difficulty: 1,
                experience_points: 50,
                task_title: "Gráf összefüggőség",
                task: "Lehet-e egy 6 csúcsú gráfnak 4 éle és összefüggő legyen?",
                solution_format: "igaz/hamis",
                first_hint: "Összefüggő gráf legalább n-1 éllel rendelkezik (n=6 → 5 él).",
                second_hint: "4 < 5 → nem lehet összefüggő",
                validated: 1
            },
            {
                id: 59,
                theme_id: 15,
                solution: "24",
                difficulty: 0,
                experience_points: 25,
                task_title: "Téglalap kerülete",
                task: "Egy 7×5 cm-es téglalap kerülete?",
                solution_format: "Egész szám",
                first_hint: "Kerület = 2×(hossz + szélesség)",
                second_hint: "2×(7+5) = 24 cm",
                validated: 1
            },
            {
                id: 60,
                theme_id: 16,
                solution: "16",
                difficulty: 0,
                experience_points: 25,
                task_title: "Számtani sorozat",
                task: "Mi a 10. tagja a 4, 6, 8,... sorozatnak?",
                solution_format: "Egész szám",
                first_hint: "Kezdőérték: 4, differencia: 2.",
                second_hint: "$a_{10} = 4 + 9×2 = 22$",
                validated: 1
            },
            {
                id: 61,
                theme_id: 17,
                solution: "3",
                difficulty: 0,
                experience_points: 25,
                task_title: "Médián számítás",
                task: "Mi a médiánja a {1,3,3,5,7} adatsornak?",
                solution_format: "Egész szám",
                first_hint: "Médián = középső érték.",
                second_hint: "Rendezett sorozat középső eleme: 3",
                validated: 1
            },
            {
                id: 62,
                theme_id: 18,
                solution: "hamis",
                difficulty: 0,
                experience_points: 25,
                task_title: "Oszthatóság",
                task: "Igaz-e: 0 prímszám?",
                solution_format: "igaz/hamis",
                first_hint: "Prímszám definíciója: pontosan két osztó.",
                second_hint: "0-nak végtelen sok osztója van.",
                validated: 1
            },
            {
                id: 63,
                theme_id: 19,
                solution: "12",
                difficulty: 0,
                experience_points: 50,
                task_title: "Szöveges sebesség",
                task: "Egy autó 90 km/h sebességgel mennyit tesz meg 8 perc alatt?",
                solution_format: "Egész szám",
                first_hint: "8 perc = 8/60 óra = 2/15 óra.",
                second_hint: "Út = 90 × (2/15) = 12 km",
                validated: 1
            },
            {
                id: 64,
                theme_id: 20,
                solution: "64",
                difficulty: 0,
                experience_points: 50,
                task_title: "Kocka térfogata",
                task: "Mekkora egy 4 cm élhosszúságú kocka térfogata?",
                solution_format: "Egész szám",
                first_hint: "Térfogat = él³",
                second_hint: "4³",
                validated: 1
            },
            {
                id: 65,
                theme_id: 21,
                solution: "0.5",
                difficulty: 0,
                experience_points: 25,
                task_title: "Koszinusz érték",
                task: "Mennyi $cos(60°)$?",
                solution_format: "Tizedes tört",
                first_hint: "Standard szög koszinusz értéke.",
                second_hint: "cos(60°) = 0.5",
                validated: 1
            },
            {
                id: 66,
                theme_id: 22,
                solution: "0.25",
                difficulty: 0,
                experience_points: 25,
                task_title: "Pénzfeldobás",
                task: "Mekkora valószínűséggel dobunk pontosan egy fejet két pénzfeldobásból?",
                solution_format: "Tizedes tört például 0.25",
                first_hint: "Kedvező esetek: {FEJ-ÍRÁS, ÍRÁS-FEJ}.",
                second_hint: "2/4 = 0.5",
                validated: 1
            },
            {
                id: 67,
                theme_id: 1,
                solution: "7",
                difficulty: 0,
                experience_points: 50,
                task_title: "Abszolútérték egyenlet",
                task: "Oldd meg: $|3x - 5| = 16$",
                solution_format: "Egész szám",
                first_hint: "Két eset: $3x -5 = 16$ és $3x -5 = -16$.",
                second_hint: "Megoldások: $7$ és $-11/3$. Csak egész válasz.",
                validated: 1
            },
            {
                id: 68,
                theme_id: 2,
                solution: "hamis",
                difficulty: 0,
                experience_points: 50,
                task_title: "Négyzetszámok",
                task: "Igaz-e: Minden négyzetszám páros?",
                solution_format: "igaz/hamis",
                first_hint: "Példa: 3² = 9 (páratlan).",
                second_hint: "Páratlan számok négyzete is páratlan.",
                validated: 1
            },
            {
                id: 69,
                theme_id: 3,
                solution: "9",
                difficulty: 0,
                experience_points: 25,
                task_title: "Egyenlet megoldása",
                task: "Oldd meg: $x/3 + 4 = 7$",
                solution_format: "Egész szám",
                first_hint: "Vonj ki 4-et: $x/3 = 3$.",
                second_hint: "Szorozd meg 3-mal: $x=9$.",
                validated: 1
            },
            {
                id: 70,
                theme_id: 4,
                solution: "5,2",
                difficulty: 2,
                experience_points: 50,
                task_title: "2018 oktv egyenletrendszer",
                task: "Oldd meg: $$2x + 3y = 16$$ $$x - y = 3$$",
                solution_format: "x,y",
                first_hint: "Fejezd ki $x$-t a második egyenletből: $x = y + 3$.",
                second_hint: "Helyettesítsd be az elsőbe: $2(y+3) + 3y = 16$ → $y=2$.",
                validated: 1
            },
            {
                id: 71,
                theme_id: 5,
                solution: "x>3",
                difficulty: 0,
                experience_points: 25,
                task_title: "Egyenlőtlenség",
                task: "Mi a megoldás a $5x - 7 > 8$ egyenlőtlenségre?",
                solution_format: "Egyenlőtlenség",
                first_hint: "Adj hozzá 7-et: $5x > 15$.",
                second_hint: "Oszd el 5-tel: $x > 3$.",
                validated: 1
            },
            {
                id: 72,
                theme_id: 6,
                solution: "2x+1",
                difficulty: 1,
                experience_points: 25,
                task_title: "Polinom osztás",
                task: "Egyszerűsítsd: $(2x^2 + x) / x$",
                solution_format: "Algebrai kifejezés",
                first_hint: "Oszd el minden tagot $x$-szel.",
                second_hint: "$2x + 1$ (feltéve, hogy $x ≠ 0$)",
                validated: 1
            },
            {
                id: 73,
                theme_id: 7,
                solution: "x!=5",
                difficulty: 0,
                experience_points: 25,
                task_title: "Értelmezési tartomány",
                task: "Add meg az $1/(x - 5)$ függvény értelmezési tartományát!",
                solution_format: "Egyenlőtlenség",
                first_hint: "A nevező nem lehet nulla.",
                second_hint: "$x - 5 ≠ 0 → x ≠ 5$",
                validated: 1
            },
            {
                id: 74,
                theme_id: 1,
                solution: "4,-1",
                difficulty: 1,
                task_title: "Abszolútérték egyenlet",
                task: "Oldd meg: $|2x - 3| = 5$",
                solution_format: "x=szám,szám",
                first_hint: "Két eset: $2x-3=5$ vagy $2x-3=-5$",
                second_hint: "Megoldások: $x=4$ és $x=-1$",
                validated: 1
            },
            {
                id: 75,
                theme_id: 2,
                solution: "hamis",
                difficulty: 0,
                task_title: "Prímszámok tulajdonsága",
                task: "Igaz-e: Ha $p$ prím, akkor $p^2 + 2$ is prím?",
                solution_format: "igaz/hamis",
                first_hint: "Próbáld ki $p=3$-mal",
                second_hint: "Ellenőrizd $p=2$ esetén is",
                validated: 1
            },
            {
                id: 76,
                theme_id: 3,
                solution: "5",
                difficulty: 1,
                task_title: "Lineáris egyenlet",
                task: "Oldd meg: $3(x - 1) = 12$",
                solution_format: "x=szám",
                first_hint: "Először ossz 3-mal",
                second_hint: "Utána adj hozzá 1-et",
                validated: 1
            },
            {
                id: 77,
                theme_id: 4,
                solution: "2,3",
                difficulty: 0,
                task_title: "Egyenletrendszer",
                task: "$$ x + y = 5 $$ $$ x - y = -1 $$",
                solution_format: "x=szám,y=szám",
                first_hint: "Add össze a két egyenletet",
                second_hint: "Az eredmény: $2x = 4$",
                validated: 1
            },
            {
                id: 78,
                theme_id: 5,
                solution: "x<=2",
                difficulty: 0,
                task_title: "Egyenlőtlenség",
                task: "Oldd meg: $3x + 4 ≥ 10$",
                solution_format: "x >= 82 vagy x <= 90",
                first_hint: "Először vonj ki 4-et",
                second_hint: "Ossz 3-mal, figyelj az egyenlőtlenség irányára",
                validated: 1
            },
            {
                id: 79,
                theme_id: 6,
                solution: "x^2-9",
                difficulty: 1,
                task_title: "Algebrai azonosság",
                task: "Bontsd fel: $(x-3)(x+3)$",
                solution_format: "polinom, például a^2-b-c, ahol a;b;c egész számok",
                first_hint: "Használd a különbségi négyzetet",
                second_hint: "$a^2 - b^2 = (a-b)(a+b)$",
                validated: 1
            },
            {
                id: 80,
                theme_id: 7,
                solution: "x>=-2",
                difficulty: 0,
                task_title: "Gyökös kifejezés",
                task: "Milyen $x$-re értelmes: $√{x + 2}$?",
                solution_format: "x>=szám",
                first_hint: "A gyök alatt nemnegatív szám",
                second_hint: "Oldd meg: $x + 2 ≥ 0$",
                validated: 1
            },
            {
                id: 81,
                theme_id: 8,
                solution: "1000",
                difficulty: 0,
                task_title: "Logaritmus számolás",
                task: "Mennyi $\\log_{10}(1000)$?",
                solution_format: "szám",
                first_hint: "10 milyen hatványa 1000?",
                second_hint: "$10^3 = 1000$",
                validated: 1
            },
            {
                id: 82,
                theme_id: 9,
                solution: "3x^2",
                difficulty: 1,
                task_title: "Deriválás",
                task: "Mi az $f(x) = x^3$ deriváltja?",
                solution_format: "kifejezés",
                first_hint: "Hatványfüggvény deriváltja: $n x^{n-1}$",
                second_hint: "$n=3$ esetén",
                validated: 1
            },
            {
                id: 83,
                theme_id: 10,
                solution: "hamis",
                difficulty: 0,
                task_title: "Halmazok",
                task: "Igaz-e: $\\{1,2\\} \\subseteq \\{2,3,4\\}$?",
                solution_format: "igaz/hamis",
                first_hint: "Minden elemnek benne kell lennie",
                second_hint: "1 nincs a második halmazban",
                validated: 1
            },
            {
                id: 84,
                theme_id: 11,
                solution: "24",
                difficulty: 0,
                task_title: "Permutáció",
                task: "Hányféleképpen ülhet 4 ember 4 székre?",
                solution_format: "szám",
                first_hint: "Permutáció: $n!$",
                second_hint: "$4! = 4×3×2×1$",
                validated: 1
            },
            {
                id: 85,
                theme_id: 12,
                solution: "k=2",
                difficulty: 0,
                task_title: "Paraméteres egyenlet",
                task: "Melyik $k$ esetén van megoldása: $x^2 + kx + 4 = 0$?",
                solution_format: "k≤szám/vagy≥",
                first_hint: "Diszkrimináns nemnegatív",
                second_hint: "$D = k^2 - 16 ≥ 0$",
                validated: 1
            },
            {
                id: 86,
                theme_id: 13,
                solution: "5",
                difficulty: 1,
                task_title: "Távolság pontok",
                task: "Két pont: $(1,2)$ és $(4,6)$. Mi a távolság?",
                solution_format: "szám",
                first_hint: "Távolságképlet: $√{(x_2-x_1)^2 + (y_2-y_1)^2}$",
                second_hint: "$√{(3)^2 + (4)^2} = 5$",
                validated: 1
            },
            {
                id: 87,
                theme_id: 14,
                solution: "igaz",
                difficulty: 0,
                task_title: "Logikai állítás",
                task: "Igaz-e: Ha esik az eső, akkor nedves az út?",
                solution_format: "igaz/hamis",
                first_hint: "Az implikáció igazságtáblázata",
                second_hint: "Ha előtag igaz, utótag is igaz kell legyen",
                validated: 1
            },
            {
                id: 88,
                theme_id: 15,
                solution: "60",
                difficulty: 0,
                task_title: "Szabályos háromszög",
                task: "Mekkora egy szabályos háromszög belső szöge?",
                solution_format: "egy egész szám, például 67",
                first_hint: "Belső szögek összege 180°",
                second_hint: "Egyenlő szögek: 180°/3",
                validated: 1
            },
            {
                id: 89,
                theme_id: 16,
                solution: "20",
                difficulty: 2,
                task_title: "Számtani sorozat",
                task: "Első tag: 2, differencia: 3. Mi a 7. tag?",
                solution_format: "szám",
                first_hint: "Képlet: $a_n = a_1 + (n-1)d$",
                second_hint: "$a_7 = 2 + 6×3$",
                validated: 1
            },
            {
                id: 90,
                theme_id: 17,
                solution: "12",
                difficulty: 0,
                task_title: "Módusz meghatározás",
                task: "Adatok: 10,12,12,15. Mi a módusz?",
                solution_format: "szám",
                first_hint: "Módusz = leggyakoribb érték",
                second_hint: "12 kétszer szerepel",
                validated: 1
            },
            {
                id: 91,
                theme_id: 18,
                solution: "2",
                difficulty: 0,
                task_title: "Legkisebb prímosztó",
                task: "Mi a 14 legkisebb prímosztója?",
                solution_format: "szám",
                first_hint: "Prímfelbontás: 14 = 2×7",
                second_hint: "A legkisebb prímosztó 2",
                validated: 1
            },
            {
                id: 92,
                theme_id: 19,
                solution: "15",
                difficulty: 2,
                task_title: "Emelt matek 2016, máj. 1/b",
                task: "Az 52941 számjegyeit leírjuk az összes lehetséges sorrendben. Ezen számok közül hány osztható 12-vel?",
                solution_format: "egész szám, például 79543",
                first_hint: "Egy szám akkor és csak akkor osztható 12-vel, ha a szám osztható 4-el és 3-al is.",
                second_hint: "Nézzük meg ezen feltételek mely esetekben teljesülnek!",
                validated: 1
            },
            {
                id: 93,
                theme_id: 20,
                solution: "150",
                difficulty: 0,
                task_title: "Térfogat számítás",
                task: "Kocka éle 5 cm. Mi a térfogata?",
                solution_format: "szám",
                first_hint: "Kocka térfogata: $a^3$",
                second_hint: "$5^3$",
                validated: 1
            },
            {
                id: 94,
                theme_id: 21,
                solution: "21400000",
                difficulty: 1,
                task_title: "Szórás kiszámítása",
                task: "Egy kisvárosban hét nagyobb üzlet található. A tavalyi évben elért, millió forintra kerekített árbevételeikről tudjuk, hogy az átlaguk 120 millió Ft, és ez megegyezik a mediánjukkal. A hét adat egyetlen módusza 100 millió Ft. Két üzletben éppen átlagos, azaz 120 millió forintos a kerekített bevétel, a legnagyobb bevétel pedig 160 millió forint volt. Számítsa ki a kerekített bevételek szórását!",
                solution_format: "egész szám, például 8743",
                first_hint: "Kerekített bevételek összege $7*120$",
                second_hint: "A medián 120 millió forint, és két 120 millió forintos árbevétel volt, ezért legfeljebb három 120 millió forintnál kisebb bevétel lehet. ",
                validated: 1
            },
            {
                id: 95,
                theme_id: 22,
                solution: "1/2",
                difficulty: 0,
                task_title: "Pénzfeldobás",
                task: "Mi a valószínűsége, hogy fej lesz?",
                solution_format: "tört",
                first_hint: "Két egyformán valószínű esemény",
                second_hint: "Kedvező/összes = 1/2",
                validated: 1
            },
            {
                id: 96,
                theme_id: 1,
                solution: "0,4",
                difficulty: 1,
                task_title: "Abszolútérték egyenlet",
                task: "Oldd meg: $|5x| = 20$",
                solution_format: "x=szám,szám",
                first_hint: "Két eset: $5x=20$ vagy $5x=-20$",
                second_hint: "Megoldások: $x=4$ és $x=-4$",
                validated: 1
            },
            {
                id: 97,
                theme_id: 2,
                solution: "igaz",
                difficulty: 0,
                task_title: "Oszthatóság",
                task: "Igaz-e: Ha egy szám osztható 12-vel, akkor 4-gyel is?",
                solution_format: "igaz/hamis",
                first_hint: "12 = 3×4",
                second_hint: "Ha osztható 12-vel, biztosan osztható 4-gyel",
                validated: 1
            },
            {
                id: 98,
                theme_id: 3,
                solution: "-2",
                difficulty: 0,
                task_title: "Egyszerű egyenlet",
                task: "Oldd meg: $2x + 5 = 1$",
                solution_format: "x=szám",
                first_hint: "Először vonj ki 5-öt",
                second_hint: "Utána ossz 2-vel",
                validated: 1
            },
            {
                id: 99,
                theme_id: 4,
                solution: "1,3",
                difficulty: 1,
                task_title: "Egyenletrendszer",
                task: "$$ x + 2y = 7 $$ $$ 2x - y = -1 $$",
                solution_format: "x=szám,y=szám",
                first_hint: "Második egyenletből fejezd ki y-t",
                second_hint: "$y = 2x + 1$, majd helyettesíts",
                validated: 1
            },
            {
                id: 100,
                theme_id: 5,
                solution: "x<1",
                difficulty: 0,
                task_title: "Exponenciális egyenlőtlenség",
                task: "Oldd meg: $3^{x} < 3$",
                solution_format: "x<szám",
                first_hint: "$3^1 = 3$",
                second_hint: "Ha alap >1, exponens <1",
                validated: 1
            },
        ];
    
    
        await Tasks.bulkCreate(testTasks, {ignoreDuplicates: true})
    }
    return Tasks;
};
